import hashlib
import secrets
import time
from typing import Tuple

class PoWController:
    """Manages Proof-of-Work challenges for bot mitigation"""
    
    def __init__(self, difficulty: int = 4):
        # Difficulty is the number of leading zeros required in the hash hex string
        self.difficulty = difficulty
        self.secret_key = secrets.token_hex(32)
        self.max_age = 300  # 5 minutes

    def generate_challenge(self) -> Tuple[str, int]:
        """Generate a new challenge salt and difficulty"""
        salt = secrets.token_hex(16)
        timestamp = int(time.time())
        # Signature ensures the salt/timestamp were generated by us
        signature = self._generate_signature(salt, timestamp)
        challenge_token = f"{salt}.{timestamp}.{signature}"
        return challenge_token, self.difficulty

    def verify_solution(self, challenge_token: str, nonce: str) -> bool:
        """Verify the nonce solves the challenge"""
        try:
            parts = challenge_token.split(".")
            if len(parts) != 3: return False
            
            salt, timestamp, signature = parts
            
            # 1. Verify expiration
            if int(time.time()) - int(timestamp) > self.max_age:
                return False
                
            # 2. Verify signature
            if signature != self._generate_signature(salt, timestamp):
                return False
                
            # 3. Verify hash solution
            # Format: salt + nonce
            data = f"{salt}{str(nonce)}".encode()
            guess_hash = hashlib.sha256(data).hexdigest()
            
            if not guess_hash.startswith("0" * self.difficulty):
                print(f"DEBUG PoW: Hash {guess_hash} does not start with {'0' * self.difficulty}")
                return False
                
            return True
            
        except Exception as e:
            print(f"DEBUG PoW: Exception in verify_solution: {e}")
            return False

    def _generate_signature(self, salt: str, timestamp: str) -> str:
        data = f"{salt}{timestamp}{self.secret_key}".encode()
        return hashlib.sha256(data).hexdigest()[:16]
